#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# AUTOSTART
killall sxhkd
sxhkd &
startbar

# We look for a non-laptop monitor to use for default, but use the laptop
# screen if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
laptopmonitor=eDP
mainmonitor="$(bspc query --monitors --names | grep -v $laptopmonitor | head -n 1)"

if [ -z $mainmonitor ]; then
	mainmonitor=$laptopmonitor
fi

# Start workspaces on the main monitor.
bspc monitor $mainmonitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

bspc config automatic_scheme alternate

bspc config border_width 1
bspc config window_gap 15
bspc config top_padding 27	# top_padding I set equal to polybar's height

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Polybar hidden when fullscreen on Youtube etc
# Name of the window taken using xprop
xdo below -t $(xdo id -n root) $(xdo id -a polybar-bar_"$mainmonitor")
